#!/bin/bash

# Setup environment
BASEPATH=$PWD
TOOLSPATH=$BASEPATH/tools
CONDA_ENVPATH=/srv/conda/envs/notebook

#export GOPATH=$BASEPATH/go
export GOBIN=$(go env GOPATH)/bin
#export GOROOT=$TOOLSPATH/go
export PATH=$GOBIN:$PATH
#JUPYTER_PATH=$CONDA_ENVPATH/.local/share/jupyter

mkdir -p \
  $GOPATH \
  $GOBIN \
  $TOOLSPATH

ENVVARSFILE=.bashrc
echo "export PATH=$GOBIN:$TOOLSPATH/go/bin:$PATH" >> $ENVVARSFILE

# Install Go
#VERSION=1.17.2
#OS=linux
#ARCH=amd64
#ARCHIVE=go$VERSION.$OS-$ARCH.tar.gz
#wget --quiet https://dl.google.com/go/$ARCHIVE
#tar -C $TOOLSPATH -xzf $ARCHIVE
#rm $ARCHIVE

# Install gophernotes
env GO111MODULE=on go get github.com/gopherdata/gophernotes
mkdir -p ~/.local/share/jupyter/kernels/gophernotes
cd ~/.local/share/jupyter/kernels/gophernotes
cp "$(go env GOPATH)"/pkg/mod/github.com/gopherdata/gophernotes@v0.7.3/kernel/*  "."
chmod +w ./kernel.json # in case copied kernel.json has no write permission
sed "s|gophernotes|$(go env GOPATH)/bin/gophernotes|" < kernel.json.in > kernel.json
